name: flagship
description: Flutter SDK for Flagship Feature management & Experiment platform for modern engineering and product teams
version: 4.1.2-beta
homepage: https://flagship.io

environment:
  sdk:  '>=2.15.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_device_type: ^0.4.0
  http: ^0.13.1
  intl: ^0.17.0
  murmurhash: ^1.0.1
  path_provider: ^2.0.11
  pausable_timer: ^1.0.0+6
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  sqflite: ^2.3.0
  json_annotation: ^4.7.0
  path: ^1.8.2
  device_info_plus: ^11.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.4
  json_serializable: ^6.5.4
  sqflite_common_ffi: ^2.3.0+2
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.6

  #test: <latest_version>

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
   #assets:
    # - images/visitor.json
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
